name: Run F1 API Extract and Load to Raw

on:
  schedule:
    - cron: '0 16 * * 0'  # Runs every Sunday at 4 PM UTC
  workflow_dispatch:

env:
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_DB: ${{ secrets.PG_DB }}

jobs:
  extract_load_raw:
    name: Extract and Load F1 API Data to Raw Schema
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out Code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: ▶️ Run API Extract + Load Script
        run: |
          python Data/_Api_Extract_Load_Raw.py